#!/usr/bin/env bash

BOTTOM=$(grep BOTTOM .env | cut -d '=' -f2 | cut -d '#' -f1)
echo

if [ $BOTTOM = "host" ]; then
  APP_PATH=$PWD
elif [ $BOTTOM = "machine" ]; then
  APP_PATH=${PWD/home/hosthome}
fi

docker run --rm -it \
  -e APP_PATH=${APP_PATH} \
  -v ${APP_PATH}/tmp:/tmp \
  -v ${APP_PATH}:/usr/src/rc \
  -w /usr/src/rc \
  node:14.9.0-buster \
  npm $@

echo
echo
